language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - VAULT_VER=0.5.2
    - VAULT_VER=0.6.0
    - VAULT_VER=0.6.1
    - VAULT_VER=0.6.2
    - VAULT_VER=0.6.3
    - PROFILE=springNext
    - PROFILE=spring5

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

install:
  - src/test/bash/start.sh

script: mvn clean verify -P${PROFILE:-ci}

after_script:
  - pkill vault

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'download'
