language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - VAULT_VER=0.5.2
    - VAULT_VER=0.6.0
    - VAULT_VER=0.6.1
    - VAULT_VER=0.6.2

install:
  - src/test/bash/start.sh

script: mvn clean verify

after_script:
  - pkill vault

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'download'
